### PR TITLE
Fix `Chunk.modules` DeprecationWarning in Webpack 3.x

### PR DESCRIPTION
**Pull request by steven-pribilinskiy**
Updates to Chunk.mapModules is not backwards compatible with Webpack 2.x due to breaking changes in webpack/webpack#4764

Following should be added to `README`:

### Install
```
# for webpack 3
npm install --save-dev extract-text-webpack-plugin
# for webpack 1, 2
npm install --save-dev extract-text-webpack-plugin@0.1.0
```

### CODE REVIEW

**Comment by steven-pribilinskiy** [comment]
`devDependencies` needs to be updated too for CI

**Comment by ghost** [comment]
Please merge...

**Comment by steven-pribilinskiy** [comment]
@ddeboer-axtion only the owner of the repo @mariusbalcytis can do that

**Comment by ghost** [comment]
Yeah i know, I was hoping he would read the message ;)

**Comment by mariusbalcytis** [comment]
Thanks for the pull request and sorry for the delay.

**Comment by steven-pribilinskiy** [comment]
ah, even don't mention it )

**Comment by arianrhodsandlot** [comment]
Bad news: `forEachModule` is also deprecated as described here: https://github.com/webpack/webpack/pull/6367 😭

**Pull request merged**
